### ISSUE TITLE
Relicense?

### ISSUE THREAD

**Issue by eight04** [StylishThemes/parse-usercss#25]
I found that the current source code of this repository is licensed under MIT. However, the original source code `usercss.js` is licensed under GPLv3. Is it OK to relicense it to MIT?

Personally, I don't really care about the license, so I agree to relicense the parser to MIT.

Ping the original author: @tophf

**Comment by tophf** [comment]
You wrote usercss.js originally but IANAL so IDK how that's relevant.
Personally I always use MIT license in my other stuff.

**Comment by eight04** [comment]
In order to modify the source code of a project, we have to comply with the license. Quoted from GPLv3:

> You must license the entire work, as a whole, under this
> License to anyone who comes into possession of a copy.  This
> License will therefore apply, along with any applicable section 7
> additional terms, to the whole of the work, and all its parts,
> regardless of how they are packaged.  This License gives no
> permission to license the work in any other way, but it does not
> invalidate such permission if you have separately received it.

Since you also committed in `usercss.js` before Jan 2018, part of `usercss.js` is modified by you and is licensed under GPLv3. If we both agree to relicense the source code of `usercss.js` to MIT, this issue can be closed. Otherwise, the license of this project should be changed to GPLv3.

**Comment by tophf** [comment]
MIT's fine by me.
