### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by DecentM** [StylishThemes/parse-usercss#3]
When the bundled code is running in the browser, an error is thrown:  

> Uncaught TypeError: require.resolve is not a function  

| | | |
| ---- | ---- | ---- |
| resolve_engine_path | @ | index.js:65 |
| exports.load | @ | index.js:25
| (anonymous) | @ | usercss.js:6
| 851../colorconverter | @ | usercss.js:617

I believe that it's originating from here: https://github.com/StylishThemes/parse-usercss/blob/39591e23fb1bc4af53c4693bab5566945e10d101/lib/usercss.js#L6

It's not immediately obvious to me why that's the case, but let me know if you need some additional testing!

**Comment by Mottie** [comment]
Hmm, I was originally thinking we'd have a full parser, but later decided to go with just parsing the metadata. So we don't even need Stylus or accord as a dependency anymore.

Try it now and see if it works.

**Comment by DecentM** [comment]
Yep, it works now. Thanks!
