### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/parse-usercss#48]
I was going to add this list to [stylus #509](https://github.com/openstyles/stylus/pull/509), but I think it fits here better:

## Number/Range

* Adding  `@var number x 'xx' ["1", 1]`, the resulting value becomes `11`.

  Maybe we should validate the units?

* Adding `@var number x 'xx' [2, 0, 7, 3, "em"]`

  The larger integer step value sets the scale to zero:

  ```js
  const value = 2;
  const step = 3;
  const decimal = step.toString().split('.')[1];
  const scale = decimal ? 10 ** decimal.length : 0; // <= change 0 to step
  if (value * scale % (step * scale)) {
    console.error('Not a multiple'); 
  }
  console.log(scale);
  // => 0
  ```

## Text

* Adding the following:

  ```
  @var text t 'text' 
  @var number x 'xx' [1, "em"]
  ```
  
  The definition becomes `:root { --t: @var number x 'xx' [1, "em"]; }` - should the text variable ignore CRLF? Or, maybe it should stop when it sees the start of a new `@var` or `@`-whatever?

**Comment by eight04** [comment]
#47, #49, #50.



> * should the text variable ignore CRLF? Or, maybe it should stop when it sees the start of a new `@var` or `@`-whatever?

We shouldn't consume all whitespaces (including `\r`) after parsing the label:
https://github.com/StylishThemes/parse-usercss/blob/0cd8058270cbf58be7a435a42dd4eab0acc6e894/lib/parse.js#L159
