### ISSUE TITLE
Step validator is broken

### ISSUE THREAD

**Issue by eight04** [StylishThemes/parse-usercss#50]
https://github.com/StylishThemes/parse-usercss/blob/0cd8058270cbf58be7a435a42dd4eab0acc6e894/lib/parse.js#L290

It should be `: 1`.

**Comment by Mottie** [comment]
Shouldn't it be set to `step` because it is used as a mod value. In my example, the value was `2` and the step was `3`.

**Comment by eight04** [comment]
It is used as the scale value. When there is no decimal, the scale is 1, so `value * scale % (step * scale)` becomes `2 * 1 % (3 * 1)` -> `2 % 3` -> `2` -> the step is invalid.

**Comment by Mottie** [comment]
Oh duh... I haven't had my caffeine yet! 😛
