### ISSUE TITLE
Invalid colors

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/parse-usercss#54]
Testing PR 509 in Stylus... I see the following definitions do not show up as invalid colors:

```css
@var color x x #1111111111111111111111
@var color y y rgba(2345, 23455, 23, 0.3)
@var color z z hsla(9999, 999999, 999, 99999);
```

results in:

![](https://user-images.githubusercontent.com/136959/46813714-d8925280-cd3c-11e8-9626-933a1ecb873b.png)

**Comment by eight04** [comment]
`usercss-meta` doesn't validate colors. The validator is implemented in `/js/meta-parser.js` here:
https://github.com/openstyles/stylus/blob/9058c06c547203ab466785bc5a54ab94fc338e27/js/meta-parser.js#L30-L38
