### ISSUE TITLE
Invalid version

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/parse-usercss#58]
This setting is not a valid semver, but no error is shown:

```
@version 0.1.1.1
```

This looks like an issue with semver-regex not matching the end of the string.

**Comment by eight04** [comment]
We should check if the match equals the entire value. Currently, the following string is also valid:
```
@version whatever 0.1.0
```

**Comment by Mottie** [comment]
> We should check if the match equals the entire value.

I agree.
