### ISSUE TITLE
Empty select option

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/parse-usercss#63]
Including an empty select option works, but should we allow it?

```
@var select x x {
  "": "red",
  "g": "green",
  "b": "blue"
}
```

**Comment by eight04** [comment]
I guess this would create an option without a label, not sure how useful it is though. Does it work in Stylus?

**Comment by Mottie** [comment]
Yes

**Comment by eight04** [comment]
I think we should add 2 validations:

1. Ensure the option name/label is not empty.
2. Ensure the option name is not duplicated.

**Comment by Mottie** [comment]
Sounds good!

**Comment by eight04** [comment]
I found that if the option name is empty, we use the label as the option name, so there will be only 2 new errors i.e. the name is duplicated and the label is empty.

> use the label as the option name

Is it the desired behavior?

**Comment by Mottie** [comment]
I can't think of a case where we'd want the label to be empty.

**Comment by eight04** [comment]
Here is the full format of an option:
```
{
  "option_name:The label": "...the value..."
}
```
If the author writes something like:
```
{
  ":A label": "A value"
}
```
It would be parsed as:
```
{
  "A label:A label": "A value"
}
```

**Comment by Mottie** [comment]
I haven't had a chance to test this, but I don't see any trimming going on in the `createOption` or the `parseSelect` functions.

```
{
  "option1_name:The label1": "...the value...",
  " :The label2": "v2",
  "option3_name: ": "v3"
}
```
